org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
forge_version=47.1.33
loader_version_range=[47,)

mixinextras_version = 0.5.3
mixinbooster_version = 0.1.3+1.20.1
mixinsquared_version = 0.3.7-beta.3

create_version = 6.0.8
create_version_number = 289
ponder_version = 1.0.91
flywheel_version = 1.0.5
registrate_version = MC1.20-1.3.3

jei_version = 15.20.0.106

mod_id=create_repair
mod_name=Create Repair: Unofficial Create Community Patch
mod_license=MIT
mod_version=1.3.0
mod_group_id=ch.voidlee.repair
mod_authors=VoidLeech, Vercte
mod_description=The Unofficial Create Community Patch; continued maintenance for 1.20.1 Create.
homepage=https://github.com/VoidLeech/Repair

# Optional Dependencies
emi_version = 1.1.22+1.20.1

cc_tweaked_version = 1.105.0
enable_cc_tweaked = false

farmers_delight_version = 1.20.1-1.2.10
enable_farmers_delight = false

journeymap_version = 1.20.1-6.0.0-beta.3+forge
journeymap_api_version = 1.20.1-2.0.0
enable_journeymap = false